export const mpdFilesActionTypes = {
    FETCH_MPD_FILES_REQUEST: 'FETCH_MPD_FILES_REQUEST',
    FETCH_MPD_FILES_SUCCESS: 'FETCH_MPD_FILES_SUCCESS',
    FETCH_MPD_FILES_FAILURE: 'FETCH_MPD_FILES_FAILURE',
}