export const moviesActionTypes = {
    FETCH_MOVIES_REQUEST: 'FETCH_MOVIES_REQUEST',
    FETCH_MOVIES_SUCCESS: 'FETCH_MOVIES_SUCCESS',
    FETCH_MOVIES_FAILURE: 'FETCH_MOVIES_FAILURE',

    FETCH_ACTION_MOVIES_REQUEST: 'FETCH_ACTION_MOVIES_REQUEST',
    FETCH_ACTION_MOVIES_SUCCESS: 'FETCH_ACTION_MOVIES_SUCCESS',
    FETCH_ACTION_MOVIES_FAILURE: 'FETCH_ACTION_MOVIES_FAILURE',
    LOAD_MORE_ACTION_MOVIES_SUCCESS: 'LOAD_MORE_ACTION_MOVIES_SUCCESS',

    FETCH_MYSTERY_MOVIES_REQUEST: 'FETCH_MYSTERY_MOVIES_REQUEST',
    FETCH_MYSTERY_MOVIES_SUCCESS: 'FETCH_MYSTERY_MOVIES_SUCCESS',
    FETCH_MYSTERY_MOVIES_FAILURE: 'FETCH_MYSTERY_MOVIES_FAILURE',
    LOAD_MORE_MYSTERY_MOVIES_SUCCESS: 'LOAD_MORE_MYSTERY_MOVIES_SUCCESS',

    FETCH_SCIFY_MOVIES_REQUEST: 'FETCH_SCIFY_MOVIES_REQUEST',
    FETCH_SCIFY_MOVIES_SUCCESS: 'FETCH_SCIFY_MOVIES_SUCCESS',
    FETCH_SCIFY_MOVIES_FAILURE: 'FETCH_SCIFY_MOVIES_FAILURE',
    LOAD_MORE_SCIFY_MOVIES_SUCCESS: 'LOAD_MORE_SCIFYY_MOVIES_SUCCESS',

    FETCH_ADVENTURE_MOVIES_REQUEST: 'FETCH_ADVENTURE_MOVIES_REQUEST',
    FETCH_ADVENTURE_MOVIES_SUCCESS: 'FETCH_ADVENTURE_MOVIES_SUCCESS',
    FETCH_ADVENTURE_MOVIES_FAILURE: 'FETCH_ADVENTURE_MOVIES_FAILURE',
    LOAD_MORE_ADVENTURE_MOVIES_SUCCESS: 'LOAD_MORE_ADVENTURE_MOVIES_SUCCESS',

    FETCH_DRAMA_MOVIES_REQUEST: 'FETCH_DRAMA_MOVIES_REQUEST',
    FETCH_DRAMA_MOVIES_SUCCESS: 'FETCH_DRAMA_MOVIES_SUCCESS',
    FETCH_DRAMA_MOVIES_FAILURE: 'FETCH_DRAMA_MOVIES_FAILURE',
    LOAD_MORE_DRAMA_MOVIES_SUCCESS: 'LOAD_MORE_DRAMA_MOVIES_SUCCESS',

    FETCH_WAR_MOVIES_REQUEST: 'FETCH_WAR_MOVIES_REQUEST',
    FETCH_WAR_MOVIES_SUCCESS: 'FETCH_WAR_MOVIES_SUCCESS',
    FETCH_WAR_MOVIES_FAILURE: 'FETCH_WAR_MOVIES_FAILURE',
    LOAD_MORE_WAR_MOVIES_SUCCESS: 'LOAD_MORE_WAR_MOVIES_SUCCESS',

    FETCH_COMEDY_MOVIES_REQUEST: 'FETCH_COMEDY_MOVIES_REQUEST',
    FETCH_COMEDY_MOVIES_SUCCESS: 'FETCH_COMEDY_MOVIES_SUCCESS',
    FETCH_COMEDY_MOVIES_FAILURE: 'FETCH_COMEDY_MOVIES_FAILURE',
    LOAD_MORE_COMEDY_MOVIES_SUCCESS: 'LOAD_MORE_COMEDY_MOVIES_SUCCESS',

    FETCH_CRIME_MOVIES_REQUEST: 'FETCH_CRIME_MOVIES_REQUEST',
    FETCH_CRIME_MOVIES_SUCCESS: 'FETCH_CRIME_MOVIES_SUCCESS',
    FETCH_CRIME_MOVIES_FAILURE: 'FETCH_CRIME_MOVIES_FAILURE',
    LOAD_MORE_CRIME_MOVIES_SUCCESS: 'LOAD_MORE_CRIME_MOVIES_SUCCESS',

    FETCH_DOCUMENTARY_MOVIES_REQUEST: 'FETCH_DOCUMENTARY_MOVIES_REQUEST',
    FETCH_DOCUMENTARY_MOVIES_SUCCESS: 'FETCH_DOCUMENTARY_MOVIES_SUCCESS',
    FETCH_DOCUMENTARY_MOVIES_FAILURE: 'FETCH_DOCUMENTARY_MOVIES_FAILURE',
    LOAD_MORE_DOCUMENTARY_MOVIES_SUCCESS: 'LOAD_MORE_DOCUMENTARY_MOVIES_SUCCESS',

    FETCH_HISTORY_MOVIES_REQUEST: 'FETCH_HISTORY_MOVIES_REQUEST',
    FETCH_HISTORY_MOVIES_SUCCESS: 'FETCH_HISTORY_MOVIES_SUCCESS',
    FETCH_HISTORY_MOVIES_FAILURE: 'FETCH_HISTORY_MOVIES_FAILURE',
    LOAD_MORE_HISTORY_MOVIES_SUCCESS: 'LOAD_MORE_HISTORY_MOVIES_SUCCESS',

    FETCH_MUSIC_MOVIES_REQUEST: 'FETCH_MUSIC_MOVIES_REQUEST',
    FETCH_MUSIC_MOVIES_SUCCESS: 'FETCH_MUSIC_MOVIES_SUCCESS',
    FETCH_MUSIC_MOVIES_FAILURE: 'FETCH_MUSIC_MOVIES_FAILURE',
    LOAD_MORE_MUSIC_MOVIES_SUCCESS: 'LOAD_MORE_MUSIC_MOVIES_SUCCESS',

    FETCH_ROMANCE_MOVIES_REQUEST: 'FETCH_ROMANCE_MOVIES_REQUEST',
    FETCH_ROMANCE_MOVIES_SUCCESS: 'FETCH_ROMANCE_MOVIES_SUCCESS',
    FETCH_ROMANCE_MOVIES_FAILURE: 'FETCH_ROMANCE_MOVIES_FAILURE',
    LOAD_MORE_ROMANCE_MOVIES_SUCCESS: 'LOAD_MORE_ROMANCE_MOVIES_SUCCESS',

    FETCH_HORROR_MOVIES_REQUEST: 'FETCH_HORROR_MOVIES_REQUEST',
    FETCH_HORROR_MOVIES_SUCCESS: 'FETCH_HORROR_MOVIES_SUCCESS',
    FETCH_HORROR_MOVIES_FAILURE: 'FETCH_HORROR_MOVIES_FAILURE',
    LOAD_MORE_HORROR_MOVIES_SUCCESS: 'LOAD_MORE_HORROR_MOVIES_SUCCESS',

    FETCH_SUSPENSE_MOVIES_REQUEST: 'FETCH_SUSPENSE_MOVIES_REQUEST',
    FETCH_SUSPENSE_MOVIES_SUCCESS: 'FETCH_SUSPENSE_MOVIES_SUCCESS',
    FETCH_SUSPENSE_MOVIES_FAILURE: 'FETCH_SUSPENSE_MOVIES_FAILURE',
    LOAD_MORE_SUSPENSE_MOVIES_SUCCESS: 'LOAD_MORE_SUSPENSE_MOVIES_SUCCESS',

}