export const authActionTypes = {
    CHECK_USER_SESSION: "CHECK_USER_SESSION",
    
    SIGN_IN_START: "SIGN_IN_START",
    SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
    SIGN_IN_FAILURE: "SIGN_IN_FAILURE",

    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
    SIGN_UP_FAILURE: "SIGN_UP_FAILURE",

    SIGN_OUT_START: 'SIGN_OUT_START',
    SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
    SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",

    GENERATE_USER_TOKEN_START: 'GENERATE_USER_TOKEN_START',
    GENERATE_USER_TOKEN_SUCCESS: 'GENERATE_USER_TOKEN_SUCCESS',
    GENERATE_USER_TOKEN_FAILURE: 'GENERATE_USER_TOKEN_FAILURE',

    RESET_USER_PASS_START: 'RESET_USER_PASS_START',
    RESET_USER_PASS_SUCCESS: 'RESET_USER_PASS_SUCCESS',
    RESET_USER_PASS_FAILURE: 'RESET_USER_PASS_FAILURE',
}