export const tmdbActionTypes = {
    FETCH_TMDB_MOVIES_REQUEST: 'FETCH_TMDB_MOVIES_REQUEST',
    FETCH_TMDB_MOVIES_SUCCESS: 'FETCH_TMDB_MOVIES_SUCCESS',
    FETCH_TMDB_MOVIES_FAILURE: 'FETCH_TMDB_MOVIES_FAILURE',

    FETCH_TMDB_CREDITS_MOVIES_REQUEST: 'FETCH_TMDB_CREDITS_MOVIES_REQUEST',
    FETCH_TMDB_CREDITS_MOVIES_SUCCESS: 'FETCH_TMDB_CREDITS_MOVIES_SUCCESS',
    FETCH_TMDB_CREDITS_MOVIES_FAILURE: 'FETCH_TMDB_CREDITS_MOVIES_FAILURE',

    FETCH_TMDB_SERIES_REQUEST: 'FETCH_TMDB_SERIES_REQUEST',
    FETCH_TMDB_SERIES_SUCCESS: 'FETCH_TMDB_SERIES_SUCCESS',
    FETCH_TMDB_SERIES_FAILURE: 'FETCH_TMDB_SERIES_FAILURE',

    FETCH_TMDB_CREDITS_SERIES_REQUEST: 'FETCH_TMDB_CREDITS_SERIES_REQUEST',
    FETCH_TMDB_CREDITS_SERIES_SUCCESS: 'FETCH_TMDB_CREDITS_SERIES_SUCCESS',
    FETCH_TMDB_CREDITS_SERIES_FAILURE: 'FETCH_TMDB_CREDITS_SERIES_FAILURE',

    FETCH_TMDB_SEASON_REQUEST: 'FETCH_TMDB_SEASON_REQUEST',
    FETCH_TMDB_SEASON_SUCCESS: 'FETCH_TMDB_SEASON_SUCCESS',
    FETCH_TMDB_SEASON_FAILURE: 'FETCH_TMDB_SEASON_FAILURE',
}