export const seriesActionTypes = {
    FETCH_SERIES_REQUEST: 'FETCH_SERIES_REQUEST',
    FETCH_SERIES_SUCCESS: 'FETCH_SERIES_SUCCESS',
    FETCH_SERIES_FAILURE: 'FETCH_SERIES_FAILURE',

    FETCH_ACTION_SERIES_REQUEST: 'FETCH_ACTION_SERIES_REQUEST',
    FETCH_ACTION_SERIES_SUCCESS: 'FETCH_ACTION_SERIES_SUCCESS',
    FETCH_ACTION_SERIES_FAILURE: 'FETCH_ACTION_SERIES_FAILURE',
    LOAD_MORE_ACTION_SERIES_SUCCESS: 'LOAD_MORE_ACTION_SERIES_SUCCESS',

    FETCH_MYSTERY_SERIES_REQUEST: 'FETCH_MYSTERY_SERIES_REQUEST',
    FETCH_MYSTERY_SERIES_SUCCESS: 'FETCH_MYSTERY_SERIES_SUCCESS',
    FETCH_MYSTERY_SERIES_FAILURE: 'FETCH_MYSTERY_SERIES_FAILURE',
    LOAD_MORE_MYSTERY_SERIES_SUCCESS: 'LOAD_MORE_MYSTERY_SERIES_SUCCESS',

    FETCH_SCIFY_SERIES_REQUEST: 'FETCH_SCIFY_SERIES_REQUEST',
    FETCH_SCIFY_SERIES_SUCCESS: 'FETCH_SCIFY_SERIES_SUCCESS',
    FETCH_SCIFY_SERIES_FAILURE: 'FETCH_SCIFY_SERIES_FAILURE',
    LOAD_MORE_SCIFY_SERIES_SUCCESS: 'LOAD_MORE_SCIFYSERIES_SUCCESS',

    FETCH_ADVENTURE_SERIES_REQUEST: 'FETCH_ADVENTURE_SERIES_REQUEST',
    FETCH_ADVENTURE_SERIES_SUCCESS: 'FETCH_ADVENTURE_SERIES_SUCCESS',
    FETCH_ADVENTURE_SERIES_FAILURE: 'FETCH_ADVENTURE_SERIES_FAILURE',
    LOAD_MORE_ADVENTURE_SERIES_SUCCESS: 'LOAD_MORE_ADVENTURE_SERIES_SUCCESS',

    FETCH_DRAMA_SERIES_REQUEST: 'FETCH_DRAMA_SERIES_REQUEST',
    FETCH_DRAMA_SERIES_SUCCESS: 'FETCH_DRAMA_SERIES_SUCCESS',
    FETCH_DRAMA_SERIES_FAILURE: 'FETCH_DRAMA_SERIES_FAILURE',
    LOAD_MORE_DRAMA_SERIES_SUCCESS: 'LOAD_MORE_DRAMA_SERIES_SUCCESS',

    FETCH_WAR_SERIES_REQUEST: 'FETCH_WAR_SERIES_REQUEST',
    FETCH_WAR_SERIES_SUCCESS: 'FETCH_WAR_SERIES_SUCCESS',
    FETCH_WAR_SERIES_FAILURE: 'FETCH_WAR_SERIES_FAILURE',
    LOAD_MORE_WAR_SERIES_SUCCESS: 'LOAD_MORE_WAR_SERIES_SUCCESS',

    FETCH_COMEDY_SERIES_REQUEST: 'FETCH_COMEDY_SERIES_REQUEST',
    FETCH_COMEDY_SERIES_SUCCESS: 'FETCH_COMEDY_SERIES_SUCCESS',
    FETCH_COMEDY_SERIES_FAILURE: 'FETCH_COMEDY_SERIES_FAILURE',
    LOAD_MORE_COMEDY_SERIES_SUCCESS: 'LOAD_MORE_COMEDY_SERIES_SUCCESS',

    FETCH_CRIME_SERIES_REQUEST: 'FETCH_CRIME_SERIES_REQUEST',
    FETCH_CRIME_SERIES_SUCCESS: 'FETCH_CRIME_SERIES_SUCCESS',
    FETCH_CRIME_SERIES_FAILURE: 'FETCH_CRIME_SERIES_FAILURE',
    LOAD_MORE_CRIME_SERIES_SUCCESS: 'LOAD_MORE_CRIME_SERIES_SUCCESS',

    FETCH_DOCUMENTARY_SERIES_REQUEST: 'FETCH_DOCUMENTARY_SERIES_REQUEST',
    FETCH_DOCUMENTARY_SERIES_SUCCESS: 'FETCH_DOCUMENTARY_SERIES_SUCCESS',
    FETCH_DOCUMENTARY_SERIES_FAILURE: 'FETCH_DOCUMENTARY_SERIES_FAILURE',
    LOAD_MORE_DOCUMENTARY_SERIES_SUCCESS: 'LOAD_MORE_DOCUMENTARY_SERIES_SUCCESS',

    FETCH_HISTORY_SERIES_REQUEST: 'FETCH_HISTORY_SERIES_REQUEST',
    FETCH_HISTORY_SERIES_SUCCESS: 'FETCH_HISTORY_SERIES_SUCCESS',
    FETCH_HISTORY_SERIES_FAILURE: 'FETCH_HISTORY_SERIES_FAILURE',
    LOAD_MORE_HISTORY_SERIES_SUCCESS: 'LOAD_MORE_HISTORY_SERIES_SUCCESS',

    FETCH_MUSIC_SERIES_REQUEST: 'FETCH_MUSIC_SERIES_REQUEST',
    FETCH_MUSIC_SERIES_SUCCESS: 'FETCH_MUSIC_SERIES_SUCCESS',
    FETCH_MUSIC_SERIES_FAILURE: 'FETCH_MUSIC_SERIES_FAILURE',
    LOAD_MORE_MUSIC_SERIES_SUCCESS: 'LOAD_MORE_MUSIC_SERIES_SUCCESS',

    FETCH_ROMANCE_SERIES_REQUEST: 'FETCH_ROMANCE_SERIES_REQUEST',
    FETCH_ROMANCE_SERIES_SUCCESS: 'FETCH_ROMANCE_SERIES_SUCCESS',
    FETCH_ROMANCE_SERIES_FAILURE: 'FETCH_ROMANCE_SERIES_FAILURE',
    LOAD_MORE_ROMANCE_SERIES_SUCCESS: 'LOAD_MORE_ROMANCE_SERIES_SUCCESS',

    FETCH_HORROR_SERIES_REQUEST: 'FETCH_HORROR_SERIES_REQUEST',
    FETCH_HORROR_SERIES_SUCCESS: 'FETCH_HORROR_SERIES_SUCCESS',
    FETCH_HORROR_SERIES_FAILURE: 'FETCH_HORROR_SERIES_FAILURE',
    LOAD_MORE_HORROR_SERIES_SUCCESS: 'LOAD_MORE_HORROR_SERIES_SUCCESS',

    FETCH_SUSPENSE_SERIES_REQUEST: 'FETCH_SUSPENSE_SERIES_REQUEST',
    FETCH_SUSPENSE_SERIES_SUCCESS: 'FETCH_SUSPENSE_SERIES_SUCCESS',
    FETCH_SUSPENSE_SERIES_FAILURE: 'FETCH_SUSPENSE_SERIES_FAILURE',
    LOAD_MORE_SUSPENSE_SERIES_SUCCESS: 'LOAD_MORE_SUSPENSE_SERIES_SUCCESS',

}