export const usersActionTypes = {
    FETCH_USER_DATA_REQUEST: 'FETCH_USER_DATA_REQUEST',
    FETCH_USER_DATA_SUCCESS: 'FETCH_USER_DATA_SUCCESS',
    FETCH_USER_DATA_FAILURE: 'FETCH_USER_DATA_FAILURE',

    UPDATE_USER_DATA_REQUEST: 'UPDATE_USER_DATA_REQUEST',
    UPDATE_USER_DATA_SUCCESS: 'UPDATE_USER_DATA_SUCCESS',
    UPDATE_USER_DATA_FAILURE: 'UPDATE_USER_DATA_FAILURE',

    RESET_USER_PASS_REQUEST: 'RESET_USER_PASS_REQUEST',
    RESET_USER_PASS_SUCCESS: 'RESET_USER_PASS_SUCCESS',
    RESET_USER_PASS_FAILURE: 'RESET_USER_PASS_FAILURE',

    CANCEL_USER_SUBSCRIPTION_REQUEST: 'CANCEL_USER_SUBSCRIPTION_REQUEST',
    CANCEL_USER_SUBSCRIPTION_SUCCESS: 'CANCEL_USER_SUBSCRIPTION_SUCCESS',
    CANCEL_USER_SUBSCRIPTION_FAILURE: 'CANCEL_USER_SUBSCRIPTION_FAILURE',

    CHECK_USER_SESSION_START: "CHECK_USER_SESSION_START",
    CHECK_USER_SESSION_SUCCESS: "CHECK_USER_SESSION_SUCCESS",
    CHECK_USER_SESSION_FAILURE: "CHECK_USER_SESSION_FAILURE",
}