export const seriesActionTypes = {
    FETCH_SERIES_REQUEST: 'FETCH_SERIES_REQUEST',
    FETCH_SERIES_SUCCESS: 'FETCH_SERIES_SUCCESS',
    FETCH_SERIES_FAILURE: 'FETCH_SERIES_FAILURE', 

    CREATE_SERIES_REQUEST: 'CREATE_SERIES_REQUEST',
    CREATE_SERIES_SUCCESS: 'CREATE_SERIES_SUCCESS',
    CREATE_SERIES_FAILURE: 'CREATE_SERIES_FAILURE',

    GET_SERIES_REQUEST: 'GET_SERIES_REQUEST',
    GET_SERIES_SUCCESS: 'GET_SERIES_SUCCESS',
    GET_SERIES_FAILURE: 'GET_SERIES_FAILURE',

    UPDATE_SERIES_REQUEST: 'UPDATE_SERIES_REQUEST',
    UPDATE_SERIES_SUCCESS: 'UPDATE_SERIES_SUCCESS',
    UPDATE_SERIES_FAILURE: 'UPDATE_SERIES_FAILURE',

    DELETE_SERIES_REQUEST: 'DELETE_SERIES_REQUEST',
    DELETE_SERIES_SUCCESS: 'DELETE_SERIES_SUCCESS',
    DELETE_SERIES_FAILURE: 'DELETE_SERIES_FAILURE'
}
